pipeline {
    agent  { label 'docker' }
    environment {
        COMPOSE_DOCKER_CLI_BUILD = '1'
        DOCKER_BUILDKIT = '1'
        COMPOSE_PROJECT_NAME = 'starter'
    }
    stages {
        stage('Build Laravel API') {
            environment {
                MYSQL_DATABASE = 'starter'
                MYSQL_USER = 'starter'
            }
            steps {
                echo 'Build stage using Docker Compose'
                withCredentials([usernamePassword(
                    credentialsId: 'database-credentials',
                    usernameVariable: 'MYSQL_ROOT_USER',
                    passwordVariable: 'MYSQL_ROOT_PASSWORD'
                )]) {
                  sh 'docker compose -f infrastructure/ci_cd/build/docker-compose.yml up -d'
                  // Wait for a moment to give the containers some time to start
                  sleep(time: 10, unit: 'SECONDS')

                  // Run the API build commands
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app cp .env.build .env'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app composer install --optimize-autoloader --no-dev'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan key:generate'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan config:clear'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan cache:clear'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan view:clear'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan route:clear'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app composer dump-autoload'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan config:cache'
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan route:cache'

                  // Run the Database migrations
                  sh 'docker exec ${COMPOSE_PROJECT_NAME}_app php artisan migrate'

                  // Run the build commands for the Admin Panel Vuejs3 SPA
                  sh "docker exec ${COMPOSE_PROJECT_NAME}_node /bin/sh -c 'cd client/admin/starter-core/dash-ui && npm install && npm run build:production'"
                  sh "docker exec ${COMPOSE_PROJECT_NAME}_node /bin/sh -c 'cd client/admin && npm install'"
                  sh "docker exec ${COMPOSE_PROJECT_NAME}_node /bin/sh -c 'cd client/admin && npm run build'"

                  // Run the build commands for the Public Nuxt3 SSR
                  sh "docker exec ${COMPOSE_PROJECT_NAME}_node /bin/sh -c 'cd client/public && npm install'"
                  sh "docker exec ${COMPOSE_PROJECT_NAME}_node /bin/sh -c 'cd client/public && npm run build'"
                }

                sh 'docker compose -f infrastructure/ci_cd/build/docker-compose.yml down'
            }
        }
        stage('Test') {
            steps {
                echo 'Test stage'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy stage'
                sh 'ansible-playbook -i /var/jenkins_data/starter/inventory infrastructure/ci_cd/deploy/starter.yml --private-key=/var/lib/jenkins/.ssh/id_rsa'
            }
        }
    }
}
